/**
 * The canonical agent-key slug (feature 014, FR-005). An agent's `key` is a
 * readable, workspace-unique HANDLE used only at the LLM/UI boundary (routing
 * handle, URLs, logs); internal references always go by `id`. This module is
 * the ONE place the slug rule lives — every creation path derives keys here and
 * nowhere else, and the backfill migration (0007) re-expresses the same rule in
 * SQL (parity is asserted by an integration test).
 *
 * Deliberately DEPENDENCY-FREE (no zod, no node:*): like `pagination.constants`,
 * it can be imported anywhere, including the browser bundle, without dragging in
 * runtime deps. Keys are generated by the SYSTEM, never by an LLM or a client.
 */

/** The seeded per-workspace orchestrator ("brigadir") key. Reserved (see below). */
export const ORCHESTRATOR_AGENT_KEY = 'brigadir';

/**
 * Keys no worker may hold. `ensureUniqueAgentKey` treats these as always taken,
 * so a persona slugging to a reserved value gets a numeric suffix instead — the
 * orchestrator's handle stays unobtainable even in a workspace whose
 * orchestrator row is momentarily absent (FR-014).
 */
export const RESERVED_AGENT_KEYS: readonly string[] = [ORCHESTRATOR_AGENT_KEY];

/** lowercase → non-[a-z0-9] runs to '-' → trim edge '-'. Empty string is possible. */
function rawSlug(input: string): string {
  return input
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '');
}

/**
 * Derive an agent key from its persona name + role (FR-005). "Hera" + "Reviewer"
 * → "hera-reviewer". If the name+role slug is empty (e.g. a non-Latin persona
 * name and no role), fall back to the role slug, then to the generic stem
 * "agent" — the result is NEVER empty (FR-008). Uniqueness is a separate step
 * (`ensureUniqueAgentKey`); this function is pure and collision-unaware.
 */
export function slugifyAgentKey(name: string, role?: string | null): string {
  const combined = rawSlug(`${name} ${role ?? ''}`);
  if (combined) return combined;
  const roleOnly = rawSlug(role ?? '');
  if (roleOnly) return roleOnly;
  return 'agent';
}

/**
 * Resolve a base key to a workspace-unique one by appending the smallest free
 * numeric suffix (`base`, `base-2`, `base-3`, …). `taken` is the set of keys
 * already used in the workspace; reserved keys count as taken. The database
 * `UNIQUE(workspace_id, key)` constraint remains the final arbiter — callers
 * retry with a refreshed `taken` set on a concurrent unique-violation.
 */
export function ensureUniqueAgentKey(base: string, taken: ReadonlySet<string>): string {
  const reserved = new Set(RESERVED_AGENT_KEYS);
  const isFree = (candidate: string): boolean => !taken.has(candidate) && !reserved.has(candidate);
  if (isFree(base)) return base;
  for (let i = 2; ; i++) {
    const candidate = `${base}-${i}`;
    if (isFree(candidate)) return candidate;
  }
}
